# apiVersion: v1
# kind: Namespace
# metadata:
#   name: model-serving
#   labels:
#     clustra.ai/model-cache-access: 'true'
#   annotations:
#     argocd.argoproj.io/sync-wave: '-10'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-serving-model-cache
  labels:
    app.kubernetes.io/managed-by: clustra-ai-service
    clustra.ai/model-cache-id: shared-hf-cache
    clustra.ai/namespace: model-serving
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
spec:
  capacity:
    storage: 400Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: clustra-model-cache-static
  mountOptions:
  - ro
  claimRef:
    namespace: model-serving
    name: model-cache
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-08d55725b600d1546::fsap-05bbbec281bc946b2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: model-serving
  labels:
    app.kubernetes.io/managed-by: clustra-ai-service
    clustra.ai/model-cache-id: shared-hf-cache
  annotations:
    argocd.argoproj.io/sync-wave: '-4'
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: clustra-model-cache-static
  volumeName: model-serving-model-cache
  resources:
    requests:
      storage: 400Gi
