apiVersion: v1
kind: Namespace
metadata:
  name: clustra
  labels:
    clustra.ai/model-cache-access: 'true'
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clustra-model-cache
  labels:
    app.kubernetes.io/managed-by: clustra-ai-service
    clustra.ai/model-cache-id: shared-hf-cache
    clustra.ai/namespace: clustra
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
spec:
  capacity:
    storage: 400Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: clustra-model-cache-static
  mountOptions:
  - ro
  claimRef:
    namespace: clustra
    name: model-cache
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0b315dc97c2254c4f::fsap-0eae3968b28abb0bc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: clustra
  labels:
    app.kubernetes.io/managed-by: clustra-ai-service
    clustra.ai/model-cache-id: shared-hf-cache
  annotations:
    argocd.argoproj.io/sync-wave: '-4'
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: clustra-model-cache-static
  volumeName: clustra-model-cache
  resources:
    requests:
      storage: 400Gi
